## 1. Импортируйте библиотеку NumPy

In [1]:
import numpy as np

## 2. Создайте массив из 10 нулей

In [2]:
mat=np.zeros(10)
print(mat)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 3. Создать массив из 10 единиц

In [3]:
mat1=np.ones(10)
print(mat1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 4. Создать массив из 10 пятерок

In [4]:
mat2=np.ones(10)*5
print(mat2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Создать массив из целых чисел от 10 до 50

In [5]:
mas=np.arange(10,50)
print(mas)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 6. Создать массив из четных чисел от 10 до 50

In [6]:
mas1=np.arange(10,50,2)
print(mas1)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


## 7. Создать матрицу 3х3 с числами от 0 до 8

In [7]:
mas2=np.arange(9).reshape(3,3)
print(mas2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 8. Создать единичную матрицу 3x3

In [8]:
mas3=np.eye(3)
print(mas3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 9. Используйте NumPy для генерации случайного числа от 0 до 1

In [9]:
p=np.random.rand ()
print (p)

0.4730696043781265


## 10. Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [10]:
mas4=np.random.randn(25)
print(mas4)

[ 1.04660355 -1.88622761 -0.26413512  1.7162627   1.09433346 -0.39950921
  0.68106981  0.26744275 -1.08347232 -0.69894349 -0.51226419  0.66188498
  0.37955924  0.3262334   0.208701    2.00176037  0.98410065  0.80289162
  0.21837903 -0.76488041 -0.052942   -1.43943946 -0.88622011  1.29849913
 -0.45447053]


## 11. Создайте матрицу используя функции библиотеки NumPy размером 10х10 со значениями от 0 до 1

In [11]:
mas5=np.arange(0.01,1.01,0.01)
mas5=mas5.reshape(10,10)
print(mas5)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


## 12. Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Эта матрица будет использоваться в последующих задачах

In [12]:
mat_st = np.arange(1,26).reshape(5,5)
print(mat_st)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


## 13. Необходимо написать код, который вернет следующую матрицу из стартовой:
array [12,13,14,15]
      [17,18,19,20]
      [22,23,24,25]

In [13]:
print(mat_st[2:,1:5])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


#14. Написать код обращения к элементу который вернет значение  20 из стартовой матрицы.

In [14]:
print(mat_st[3][4])

20


#15. Написать код к стартовой матрице, который воспроизводит вывод
array ([[2],[7],[12]])

In [15]:
print(mat_st[:3,1])

[ 2  7 12]


#16. Написать код к стартовой матрице задачи l , который воспроизводит вывод 
array [21,22,23,24,25]

In [16]:
print(mat_st[4:,:])

[[21 22 23 24 25]]


#17. Написать код к стартовой матрице задачи l , который воспроизводитвывод
array [16,17,18,19,20] [21,22,23,24,25]

In [17]:
print(mat_st[3:,:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


#18. Получить сумму всех значений в стартовой матрице mat

In [18]:
print(mat_st.sum())

325


#19. Получить стандартное отклонение в стартовой матрице mat

In [19]:
print(mat_st.std())

7.211102550927978


#20. Получить сумму значений в колонках в стартовой матрице mat


In [20]:
print(mat_st.sum(axis=0))

[55 60 65 70 75]


в строках 

In [21]:
print(mat_st.sum(axis=1))

[ 15  40  65  90 115]
